import type { UserRole } from "../types/userRole"
export const ROLE_NAVS: Record<UserRole, string[]> = {
    ADMIN: [
        "Dashboard",
        "Institute Registration",
        "Verification",
        "Staffing",
        "Academics",
        "Workload",
        "NOC",
        "Assets",
        "Legal Cases",
        "Students",
        "RTI",
        "Grievance",
        "Reports",
    ],
    INSTITUTE: [
        "Dashboard",
        "Institute Registration",
        "Staffing",
        "Academics",
        "Workload",
        "NOC",
        "Assets",
        "Legal Cases",
        "Students",
        "RTI",
        "Grievance",
        "Settings",
    ],
    JD: [
        "Dashboard",
        "Verification",
        "Staffing",
        "Workload",
        "NOC",
        "RTI",
        "Grievance",
        "Reports",
        "Settings",
    ],
    DIRECTOR: [
        "Dashboard",
        "Verification",
        "NOC",
        "RTI",
        "Grievance",
        "Reports",
        "Settings",
    ],
    SECRETARY: [
        "Dashboard",
        "Verification",
        "NOC",
        "RTI",
        "Grievance",
        "Reports",
        "Settings",
    ],
}